version: "3.7"
services:
    app:
        build:
            args:
                user: jrlc-bid
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: jrlc-bid-laravel
        container_name: jrlc-bid-laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        #        command: bash -c 'php artisan migrate'
        #        depends_on:
        #            -   db
        #        links:
        #            -   db
        volumes:
            - ./:/var/www
        networks:
            - jrlc-bid-laravel

    db:
        image: mysql:8.0.26
        container_name: jrlc-bid-laravel-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - jrlc-bid-laravel

    nginx:
        image: nginx:alpine
        container_name: jrlc-bid-laravel-nginx
        restart: unless-stopped
        ports:
            - '8000:80'
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - jrlc-bid-laravel

networks:
    jrlc-bid-laravel:
        driver: bridge
